### ISSUE TITLE
How to get this server to understand ST's `var(--greenish)` etc?

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP-css#14]
When doing CSS for plugin development the best choice of colors are the `var(--greenish)` and `var(--redish)` etc, because they will match the user's color scheme. However this server doesn't display color boxes for those colors.

**Comment by rchl** [comment]
These are ST specific variables. The server has no way of knowing they exist.

**Comment by rwols** [comment]
Perhaps we can deduce the RGB colors and send them in the `workspace/didChangeConfiguration` notification. The server can then lookup var colors that it cannot deduce just from the file.

**Comment by rchl** [comment]
But this server can't even understand css variables, it seems:
![Screenshot 2020-06-07 at 14 23 08](https://user-images.githubusercontent.com/153197/83968572-76e80a00-a8ca-11ea-9c14-e0764c117de8.png)

**Comment by predragnikolic** [comment]
There is nothing that can be done in the LSP-css repo to achieve this,
this feature should be opened at css language server repo.

**Comment by predragnikolic** [comment]
Feel free to open a feature request at the server repo.
I will close this as there is nothing that this plugin can do about it.
