### ISSUE TITLE
NPM version or script

### ISSUE THREAD

**Issue by predragnikolic** [sublimelsp/LSP-css#18]
Should we use the npm version - https://www.npmjs.com/package/vscode-css-languageservice?activeTab=dependents 
- pros: dependabot creates PRs when new releases are available
-  cons: can't guarantee that the npm package will be maintained

or script for updating this repo 
- pros: ability to have latest changes
- cons: maybe forget to run the script until someone mentions you to run it :)

I seriously don't know what approach is better :)

**Comment by rchl** [comment]
Using npm package is better unless there is something wrong with the npm package or it's outdated.

I'm not sure why we've switched to building manually. It was done in #2. The most likely reason is that the npm package was outdated but it seems to be up to date now.

**Comment by jfcherng** [comment]
because https://github.com/sublimelsp/LSP-css/pull/2

---

Does npmjs.com/package/vscode-css-languageservice?activeTab=dependents working? I mean, is it a LSP server?

**Comment by rchl** [comment]
> But, note that the NPM package proposed by @predragnikolic is different from what [we are using now](https://github.com/vscode-langservers/vscode-css-languageserver), which [depends on that NPM package](https://github.com/vscode-langservers/vscode-css-languageserver/commit/71af9d74ed9c5d5e6021428ab5288ab83fd3fc6d#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R13).

Oh, yes. The "*service" one is what the "*server* is using. We can't use "*service" directly.

The one we could use is released as https://www.npmjs.com/package/vscode-css-languageserver-bin but that one is outdated.

So that's why we are building manually.

**Comment by predragnikolic** [comment]
Yes, now it makes sense, thanks for the clarification. 🙂
