### ISSUE TITLE
Only LSP auto completion suggestion

### ISSUE THREAD

**Issue by marcoSven** [sublimelsp/LSP-css#20]
Is it possible to disable the build-in CSS auto-completion? 

<img width="390" alt="Screen Shot 2020-11-18 at 6 10 08 PM" src="https://user-images.githubusercontent.com/3860298/99612183-f1fd3280-29c9-11eb-817e-9099dba4239f.png">

**Comment by rchl** [comment]
When you have a *.css file opened, go to `Preferences: Settings - Syntax specific` in Command Pallette and set this setting:
```js
"disable_default_completions": true
```
This semi-hidden setting currently exists for CSS and HTML syntaxes.

**Comment by marcoSven** [comment]
Thank you!
