### ISSUE TITLE
Configure LSP

### ISSUE THREAD

**Issue by marcoSven** [sublimelsp/LSP-css#21]
Can I disable this suggestion that appears highlighted green inline as I type, it is conflicting with the auto complete below.

<img width="370" alt="Screen Shot 2020-11-18 at 6 11 53 PM" src="https://user-images.githubusercontent.com/3860298/99612545-a303cd00-29ca-11eb-8991-85c2492fa867.png">

Can I disable the color preview square box? I am using another plugin that generates the same.

<img width="167" alt="Screen Shot 2020-11-18 at 6 21 40 PM" src="https://user-images.githubusercontent.com/3860298/99612690-eeb67680-29ca-11eb-9de4-fb21bf8b8fec.png">

**Comment by jfcherng** [comment]
> Can I disable this suggestion that appears highlighted green inline as I type, it is conflicting with the auto complete below.
> 
> <img alt="Screen Shot 2020-11-18 at 6 11 53 PM" width="370" src="https://user-images.githubusercontent.com/3860298/99612545-a303cd00-29ca-11eb-8991-85c2492fa867.png">

It's from Emmet. Check its `abbreviation_preview` setting.



> Can I disable the color preview square box? I am using another plugin that generates the same.
> 
> <img alt="Screen Shot 2020-11-18 at 6 21 40 PM" width="167" src="https://user-images.githubusercontent.com/3860298/99612690-eeb67680-29ca-11eb-9de4-fb21bf8b8fec.png">

You can add the following setting to `LSP` (not `LSP-CSS`).
```js
    "disabled_capabilities": [
        "colorProvider",
    ],
```

**Comment by marcoSven** [comment]
Thank you!
