### ISSUE TITLE
Autocompletion Errors

### ISSUE THREAD

**Issue by dwhenson** [sublimelsp/LSP-css#23]
Any time I try and auto-complete with an LSP suggestion I get the following error 'command editor.action.triggerSuggest failed. Reason: Unhandled method workspace/executeCommand (-32601)' 

If I ignore it (by clicking OK) I get this: "property value expected ​css:css-propertyvalueexpected". Any advice on how to resolve this issue would be appreciated. (Other LSP's  are working fine).

**Comment by predragnikolic** [comment]
What language server are you using? 
Have you installed a LSP-plugin or have you configured a language server manually?

**Comment by predragnikolic** [comment]
I published a new release, so soon it will be on Package Control.

**Comment by dwhenson** [comment]
Seems to work great now!
