### ISSUE TITLE
Autocomplete flex-direction/flex-basis on tab

### ISSUE THREAD

**Issue by dwhenson** [sublimelsp/LSP-css#25]
Apologies another smaller issue...

When trying to autocomplete some values the suggestions do not match what is completed. 

Examples include 'flex-direction' completing to 'float: dirc' and 'flex-basis' completing to 'float: b'.

Sublime text's suggestions are also not suppressed as in other LSPs. 

Please let me know if you need more details or information on this.

**Comment by jfcherng** [comment]
My first guess would be the "autocompletion" provided by Emmet confuses you.

**Comment by dwhenson** [comment]
Good first guess. Disabling Emmet seems to solve the completion problem. I’m still getting duplicate suggestions though, with other LSPs seem to have suppressed.

**Comment by rwols** [comment]
You can set `"only_show_lsp_completions": false` in Preferences/User/LSP.sublime-settings if you don't want word completions from ST. Or, if you're using ST4, set `"inhibit_word_completions": true`.

**Comment by dwhenson** [comment]
Thanks. I had those settings already included and the seem to work for other LSP languages but not CSS. Where it still shows ST suggestions. 

I just tried disabling the CSS3 package and it has now improved as ST now only seems to suggest text (I.e with the “abc”) label at the end of the suggestion. 

I’d still prefer it not to suggest that though.

**Comment by predragnikolic** [comment]
>  I’m still getting duplicate suggestions though, with other LSPs seem to have suppressed.

<img width="407" alt="Screenshot 2021-01-17 at 15 13 15" src="https://user-images.githubusercontent.com/22029477/104845594-94f10080-58d6-11eb-99a8-18ec321ce9f2.png">


You can remove the duplicated completions by doing these steps:
1. Open a `*.css` file,
2. Chose `Preferences > Settings - Syntax Specific`, that will open `CSS.sublime-settings`
3. Add this to `CSS.sublime-settings`:
```json
// These settings override both User and Default settings for the CSS syntax
{
	"disable_default_completions": true
}
```

After that, you wont get duplicated completions.

<img width="515" alt="Screenshot 2021-01-17 at 15 13 22" src="https://user-images.githubusercontent.com/22029477/104845602-9ae6e180-58d6-11eb-91c7-4770bc75eded.png">

**Comment by predragnikolic** [comment]
If you still have an issue with this feel free to reopen it.
