### ISSUE TITLE
SASS indented

### ISSUE THREAD

**Issue by frenchysdf** [sublimelsp/LSP-css#29]
Hi guys, this is more of a question than an issue (or it could be); I use SASS indented, does this LSP support it (I only see CSS, SCSS, LESS)?

**Comment by predragnikolic** [comment]
Unfortunately the language server that we use doesn't support the SASS syntax.

See:
https://github.com/microsoft/vscode-css-languageservice/issues/33#issuecomment-327813548

https://github.com/microsoft/vscode-css-languageservice/issues/158#issuecomment-725679373

**Comment by predragnikolic** [comment]
I discovered that a different language server somehow addedd support for SASS - https://github.com/johnsoncodehk/volar/issues/20#issuecomment-786897510

**Comment by predragnikolic** [comment]
I found out how volar added support for SASS -
https://github.com/johnsoncodehk/volar/commit/d326f13fafe14632d93907670b033aa779e8eab7#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R146

> style: css, scss, less, postcss (stylus, sass has limited support)
> If use postcss / stylus / sass, you need to install additional extension for syntax highlighting. I tried these and it works, you can also choose other.

In other words, we could recommend the same and that is install the SASS sublime text plugin for limited support.
----

Currently I am not aware of any language server that provides SASS indent syntax.
I would suggest opening an issue at microsoft/vscode-css-languageservice but after seeing two closed issues that asked for the same feature request, I would not have high hopes... But you can try.

I will close this issue as I don't see how we could fix it on our end here.
