### ISSUE TITLE
Cannot override 'Unknown property' warnings

### ISSUE THREAD

**Issue by saneef** [sublimelsp/LSP-css#36]
I'm not able to override "Unknown property" warning using settings.

This is what I set in`LSP-css.sublime-settings`:
```json
{
  "css.lint.validProperties": ["accent-color"],
  "scss.lint.validProperties": ["accent-color"]
}
```

<img width="754" alt="Screenshot 2021-09-08 at 23 03 51" src="https://user-images.githubusercontent.com/81863/132557221-0a963cf7-fed6-4deb-b15c-61ef2f249496.png">

**Comment by rwols** [comment]
Install LSP-json and it’ll guide you to the misconfigurarion in your LSP-css.sublime-settings

**Comment by saneef** [comment]
I installed LSP-json, and it's not showing any errors or warning. :(

<img width="649" alt="Screenshot 2021-09-09 at 09 26 31" src="https://user-images.githubusercontent.com/81863/132620301-5d57d5e0-c3b3-4500-a0d6-c1b2c89273cc.png">

**Comment by jfcherng** [comment]
```js
{
    "settings": {
        "css.lint.validProperties": [
            "accent-color"
        ],
        "scss.lint.validProperties": [
            "accent-color"
        ]
    }
}
```

**Comment by jfcherng** [comment]
> I installed LSP-json, and it's not showing any errors or warning. :(

LSP-json doesn't provide errors for this. Weird...

**Comment by saneef** [comment]
Ah! 🙈 

Thanks @jfcherng and @rwols!

**Comment by rchl** [comment]
> > I installed LSP-json, and it's not showing any errors or warning. :(
> 
> LSP-json doesn't provide errors for this. Weird...

I think it's a limitation of the JSON schema where when using `allOf` we can't also use `additionalProperties: false`
