### ISSUE TITLE
Configurations from `css.customData` not applied

### ISSUE THREAD

**Issue by titouanmathis** [sublimelsp/LSP-css#37]
I have a configuration file defining the at-directives from Tailwind in the same folder as my `LSP-css.sublime-settings` which does not seem to be picked up by the server as I still get warnings for "Unkown at rule". 

**LSP-css.sublime-settings**
```json
{
	"settings": {
		"css.customData": [
			"./lsp-css-custom-data-tailwind.json"
		]
	}
}
```

**lsp-css-custom-data-tailwind.json**
```json
{
	"version": 1.1,
	"atDirectives": [
		{
			"description": "Tailwind",
			"name": "@tailwind"
		},
		{
			"description": "Apply.",
			"name": "@apply"
		},
		{
			"description": "Screens.",
			"name": "@screen"
		}
	]
}
```

I think there might be an issue with the path resolution as it is relative. The data seems to be read in [customData.js#22](https://github.com/sublimelsp/LSP-css/blob/master/language-server/css-language-features/server/out/customData.js#L22), but I do not know how to debug this part to check if the path is correctly resolved.

**Comment by rchl** [comment]
That json file should likely be at your projects root directory.

Having it alongside `LSP-css.sublime-settings` will surely not work.

**Comment by titouanmathis** [comment]
> Also, the idea with those kinda of settings is that you set those per-project (Project: Edit Project from the command palette).

I did not know that, thanks for the tip!
