### ISSUE TITLE
Is there a way to turn off color previews?

### ISSUE THREAD

**Issue by trych** [sublimelsp/LSP-css#38]
Hi there,

I am using another package for color previews, so once the lsp color previews kick in I actually have two color previews.

<img width="223" alt="20211009-185334_Screenshot_SublimeText" src="https://user-images.githubusercontent.com/9803905/136667406-52be7057-0626-476b-ae85-27d0a748ebc4.png">

As I would like to keep using the other package (it offers some extra features), is there some way to turn of the lsp's color previews?

Thanks!

**Comment by jfcherng** [comment]
In LSP-css settings,
```js
{
    "disabled_capabilities": {
        // prefer the ColorHelper plugin
        "colorProvider": true,
    },
}
```
