### ISSUE TITLE
Duplicate suggestion with built-in Sass package

### ISSUE THREAD

**Issue by lzaaldian** [sublimelsp/LSP-css#39]
Hi, I'm using Sublime Text 4 with LSP-css and [Sass package](https://packagecontrol.io/packages/Sass). I use Sass package for syntax highlighting but it appears to show duplicate suggestion.

This is an example of coding in `.scss` file.

<img width="423" alt="Jepretan Layar 2021-11-21 pukul 4 58 40 PM" src="https://user-images.githubusercontent.com/3760093/142757703-b172f247-7338-4063-820d-d13b660f7b0a.png">

---

If I disable the package by adding `"Sass"` in `"ignored_packages"` in Preferences (press `Ctrl + ,` on Mac) like this, both syntax highlighting and suggestion feature won't work

```json
"ignored_packages":
[
    ...,
    "Ruby",
    "Sass",
    "Scala",
    ...,
]
```

---

Ideally, only suggestion from LSP-css will show because it has **More** button which will show short documentation when clicked. Or, only one of them will be showed.

Any help on this is greatly appreciated.

**Comment by jfcherng** [comment]
https://github.com/braver/SublimeSass/blob/master/sass_completions.py

**Comment by rchl** [comment]
Adding entry in the FAQ for this - #40

**Comment by lzaaldian** [comment]
Awesome! Thank you @jfcherng @rchl 🙌
