### ISSUE TITLE
The server compilation script emits errors during compilation

### ISSUE THREAD

**Issue by jfcherng** [sublimelsp/LSP-css#47]
Script: https://github.com/sublimelsp/LSP-css/blob/be5f00bc7f64fa8dc6b74a214b82486209fef0e6/language-server/compile-language-server.sh

![image](https://github.com/sublimelsp/LSP-css/assets/6594915/cf5f0557-4ad0-4585-8b76-a4bbd8506864)

I failed to fix that. LSP-html suffers too.

**Comment by rchl** [comment]
My guess is that it's a matter of using the same node version that VSCode uses for development. But I can have a look later.

**Comment by jfcherng** [comment]
I am using the latest LTS v20.10.0 on Windows x64 if that matters. 🤔
