### ISSUE TITLE
Issue with tailwind and lsp_format_on_save

### ISSUE THREAD

**Issue by kxng0109** [sublimelsp/LSP-css#49]
I use lsp-tailwindcss, and it seems like lsp_format_on_save breaks it. 
For classes that require a semi-colon, e.g. md:text-3xl or hover:bg-blue-500, it adds a whitespace after saving the css file which breaks tailwindcss. 
So instead of 'hover:bg-blue-500', it formats it to 'hover: bg-blue-500'. 
I had to disable lsp_format_on_save, but is there anyway this can be fixed?

**Comment by jfcherng** [comment]
supposely we need to recompile the server

**Comment by rchl** [comment]
There is no new changes upstream. I've assumed that the it's the dependency updates that were in latest changes that are supposed to solve this.

**Comment by kxng0109** [comment]
Another issue similar to the first, it's adding spacing in-between custom classes that require an underscore. 

For example `grid-cols-[repeat(auto-fill,_260px)` is formatted as `grid-cols-[repeat(auto-fill, _260px)`

**Comment by predragnikolic** [comment]
@kxng0109 those are all server issues. 
It would be best to report at https://github.com/microsoft/vscode-css-languageservice/issues or https://github.com/beautify-web/js-beautify

**Comment by rchl** [comment]
I don't think LSP-css is supposed to understand tailwind css. You might want to just disable it.
