### ISSUE TITLE
Error displaying contents

### ISSUE THREAD

**Issue by kapitanluffy** [sublimelsp/LSP-css#9]
Here is a screenshot of what is happening.

![image](https://user-images.githubusercontent.com/485799/80448869-394da400-8950-11ea-9d76-edc43b8d4661.png)

**Comment by rchl** [comment]
I can't really see it here, I think (or maybe my colors don't have enough contrast to see it?)
![Screenshot 2020-04-28 at 09 22 05](https://user-images.githubusercontent.com/153197/80458833-be759080-8931-11ea-9e81-0f960477e25c.png)

**Comment by rchl** [comment]
The response looks like this.
```
{
    "range": {
        "start": {
            "line": 16,
            "character": 2
        },
        "end": {
            "line": 16,
            "character": 13
        }
    },
    "contents": {
        "kind": "markdown",
        "value": "Determines which page-based occurrence of a given element is applied to a counter or string value.\n\nSyntax: normal | none | [ <content-replacement> | <content-list> ] [/ <string> ]?\n\n[MDN Reference](https://developer.mozilla.org/docs/Web/CSS/content)"
    }
}
```
So it looks like the `<string>` tag is what makes it highlighted for you.
In any case the tags should not be parsed in this context. Not sure if that is an LSP or server issue.

**Comment by rwols** [comment]
Yes the server should escape open and close tags if it claims to be markdown.

**Comment by rwols** [comment]
If it were plaintext, it would be our responsibility to escape HTML tags

**Comment by predragnikolic** [comment]
This should be fixed on ST4 with https://github.com/sublimelsp/LSP/pull/1046 :)

**Comment by rchl** [comment]
I don't think it's fixed by us. This looks like a server bug where server provides markdown content with unescaped `<string>` and we just parse it as HTML tag. The `<string>` is supposed to show as a literal string in this case so server should escape it.

But it's not our fault so it should be closed anyway. Should be reported on the server repo instead.
